cyberark/conjur-service-broker

app/models/service_binding.rb
features/bind.feature
lib/conjur_client.rb

Added Conjur version to the creds returned on bind so that the version will be accessible to the buildpack.
[Jenkins build](https://jenkins.conjur.net/job/cyberark--conjur-service-broker/job/CONJ-4693-SB-returns-version-on-bind/)
[Jira story](https://ca-il-jira.il.cyber-ark.com:8443/browse/CONJ-4693)

CONJ-4693 - SB returns Conjur version on bind

---

lib/conjur_client.rb

Closes #36 
This update addresses an issue where the SB was attempting to parse an empty `CONJUR_SSL_CERTIFICATE` env var.

36 - Service broker correctly handles empty `CONJUR_SSL_CERTIFICATE` env var

---

bin/health-check.rb

https://ca-il-jira.il.cyber-ark.com:8443/browse/CONJ-4711
Tested via `test.sh` script:
```
root@b2f81d44f2f8:/app# ./bin/health-check.rb
Successfully validated Conjur credentials.
./bin/health-check.rb:26:in `<main>': Error: There is an issue with your Conjur configuration. Please verify that your Conjur policy contains a host factory named 'apps' under the 'root' policy. (RuntimeError)
```

Conj 4711  service broker has health check that verifies hf existence for v4

---

README.md

This PR updates the README for clarity, to be consistent with our other docs / tutorials, and to include recommendations that a Conjur Host identity is used for the Service Broker configuration.

CONJ-4597 - Update README to recommend Host for SB configuration

---

CHANGELOG.md
README.md
app/models/service_binding.rb
ci/configure_v5.sh
ci/policy.yml
docker-compose.yml
features/bind.feature
features/step_definitions/response_steps.rb
features/support/world.rb
lib/conjur_client.rb
spec/models/service_binding_spec.rb
test.sh

This PR updates the service broker to check its host identity (`ConjurClient.authn_login`) for an annotation of the form `platform: [platform-name]`, where `platform-name` might be `cloudfoundry`, `pivotalcloudfoundry`, `kubernetes`, or `openshift`.
If the SB host identity has a `platform` annotation, then a `[platform-name]: true` annotation will be added to all hosts added to Conjur policy by the service broker.
Only the `alt-policy-name` bind test uses the host identity with its platform annotation in the SB config, so that test was updated to confirm that the host the SB added on bind has the appropriate annotation in Conjur.
[Jenkins run](https://jenkins.conjur.net/job/cyberark--conjur-service-broker/job/CONJ-4776-SB-adds-annotation-to-hosts/)
[Jira …

CONJ-4776 SB adds annotation to hosts

---

Gemfile
Gemfile.lock

This change ensures rack is above or at version 2.0.6. 
**Note** that this does not change any dependencies, as the correct version was already being pulled from upstream.
Connected to #64 
[Jenkins Build](https://jenkins.conjur.net/job/cyberark--conjur-service-broker/job/64-pin-rack/1/)

Pin rack at version 2.0.6

---

CHANGELOG.md
Gemfile
Gemfile.lock
README.md
app/controllers/application_controller.rb
app/controllers/bind_controller.rb
app/models/org_space_policy.rb
app/models/service_binding.rb
ci/integration/policy/entitle-service-broker.yml
ci/integration/policy/pcf/service-broker.yml
features/bind.feature
features/integration.feature
features/step_definitions/integration_steps.rb
features/support/cf_helper.rb
features/support/world.rb
lib/conjur_client.rb
spec/controllers/bind_controller_spec.rb
spec/models/org_space_policy_spec.rb
spec/models/service_binding_spec.rb
spec/spec_helper.rb

This PR updates the Conjur service broker to include the Organization GUID and Space GUID from PCF into the host identity for the application, and to add the applications to Conjur `!layers` for the org and space. This allows a Conjur operator to permit an application to access resources based on the Space or Org in which it is deployed, rather than only on the application bind id itself.
Connected to #63 
Jenkins: https://jenkins.conjur.net/job/cyberark--conjur-service-broker/job/63-add-host-to-org-space-policy/
The acceptance criteria for this change are below, with references to the relevant PR changes:
> The flow changes to add the host to the space layer are in: https://github.com/cyberark/conjur-service-broker/pull/73/commits/122c41f3a6fdc7ebcbc2c2db546fd8c4c9f3677a
> See changes in …

Add Host to Org and Space Policy Automatically on Bind

---

ci/integration/test-app/Gemfile
ci/integration/test-app/Gemfile.lock

Connected to #74 
Minor update to bump the versions of rack and sinatra in the CI test app to address vulnerability warnings. These are not critical errors since they are in a test app used for CI tests only, but I've updated them in any case.
**Note**: I also added `unset CF_API_ENDPOINT` to the method that runs the v4 test suite, bc it was re-running the integration test which (as I understand it) is running against an already deployed v5 Conjur instance. Also, it could be clearer in the docs (maybe in the integration test section of CONTRIBUTING.md?) what exactly the integration tests are running as part of the build - I don't know if it's running against Conjur v5 EE or Conjur OSS.

Bump rack and sinatra versions in test app

---

CHANGELOG.md
README.md
app/controllers/application_controller.rb
app/controllers/bind_controller.rb
app/controllers/provision_controller.rb
app/models/conjur_api_model.rb
app/models/org_space_policy.rb
app/models/schemas/provision.json
app/models/service_binding.rb
app/models/service_instance.rb
app/models/service_instance_policy.rb
ci/integration/policy/app.yml
ci/integration/test-app/secrets.yml
ci/integration/test-app/test_app.rb
features/integration.feature
features/provision.feature
features/step_definitions/integration_steps.rb
features/support/cf_helper.rb
features/support/conjur_helper.rb
features/support/hooks.rb
features/support/world.rb
lib/typed_env.rb
spec/controllers/deprovision_controller_spec.rb
spec/controllers/provision_controller_spec.rb
spec/controllers/unbind_controller_spec.rb
spec/models/org_space_policy_spec.rb
spec/models/service_instance_policy_spec.rb
spec/models/service_instance_spec.rb

This PR updates the service broker to automatically generate the policy for a CF org and space when the service is provisioned inside of a space.
Additionally, when the service is de-provisioned, it will clean up the policy for that space. This behavior may be disabled by setting the environment variable `CONJUR_PRESERVE_POLICY` to `true`.
Connected to #70 
Jenkins Build:
https://jenkins.conjur.net/job/cyberark--conjur-service-broker/job/70-provision-space-policy/
AC:
> https://github.com/cyberark/docs-cyberark-conjur-service-broker/issues/4
> https://github.com/conjurinc/cloudfoundry-conjur-tile/issues/14

Generate Org and Space Policy on Provision

---

bin/health-check.rb
features/health-check.feature

Connected to #88 
This PR updates the follower url check from `unless ... nil?` to `if present?` to account for a blank (or whitespace string) value.

Update health check to treat an empty string for follower as not configured

---

README.md
ci/test.sh

Connected to #116 
This PR makes the following updates to the README documentation:
* Add section on privileging applications using the org/space layers or the application host identity.
* Include considerations when using Space Host Identities.
* Add section on rotating host API keys.

Update README to document Space Host Identity Usage

---

app/models/org_space_policy.rb
app/models/service_binding/conjur_v5_space_binding.rb
lib/conjur_client.rb
spec/lib/conjur_client_spec.rb

Connected to #121 
This PR updates the Org and Space policy checks to use the follower URL if configured.

Switch OrgSpacePolicy to use Follower URL if configured

---

secrets.yml

Connected to https://github.com/conjurinc/cloudfoundry-conjur-tile/issues/32
This PR removes the CI environment URLs from `secrets.yml` and pulls them via Summon as well.

Fetch CI environment URLs via summon

---

Gemfile
Gemfile.lock

This updates ActionView to 5.2.4.2 to address
https://nvd.nist.gov/vuln/detail/CVE-2020-5267

Update rails gems to 5.2.4.2

---

CHANGELOG.md
Dockerfile
Dockerfile.test
Gemfile

We were installing the development and test gems in the main container and in the test container, which was causing trivy warnings on the main container. This change removes the extra gems from the main container. During testing the changes, we found that the listen gem was required for tests, and needed to be present in the main container and the test container for the tests to pass, so we moved it out of the development group. 
Fixes #159.

Remove test/development gems from main Docker image

---

.trivyignore

Since we don't use the included kernel when being run by Docker, these
CVEs are irrelevant to the project so they have been marked as ignored.
Fixes #159

Added irrelevant kernel CVEs to `.trivyignore`

---

.dockerignore
.gitignore
Jenkinsfile

We want to be able to publish the same file that passed tests so this
ensures that Jenkins has it available
Fixes #163

Save artifacts built by CI `master` pipeline

---

Jenkinsfile

Since sequential testing of the docker image and unit tests don't
ovrlap, their testing stages can run in parallel to speed up cycles on
this repo. Also, since we may want the `zip` available even if image
scans fail, move that step to a conditional one for the test stage.

Speed up builds by running all tests and checks in parallel

---

Gemfile.lock

Reverts cyberark/conjur-service-broker#187
In #186 we got the build back to green. There are [issues](https://github.com/puma/puma/issues/2286) with puma 3.12.6 that mean our pipeline fails when we use that version. Let's revert back to 3.12.5 until we can demonstrate that 3.12.6 is working.

Revert "Bump puma from 3.12.5 to 3.12.6"

---

Jenkinsfile

The service broker is built with a hardcoded "service_id" and "plan_id" in the [catalog](https://github.com/cyberark/conjur-service-broker/blob/master/config/catalog.yml), which means in our e2e tests that deploy the service broker to a remote CF foundation, if two pipelines run at once one may artificially fail because there is already a service broker deployed in the foundation with the same service_id. This commit locks the pipelines so only one can run at once, which may mean pipelines take longer to run, but will help avoid the collision issue until we come up with another solution (such as dynamically updating the service_id in our pipelines).
Connected to #173

Add lock to Jenkinsfile to stop collisions

---

CONTRIBUTING.md
README.md
app/models/service_binding/conjur_v4_app_binding.rb
app/models/service_binding/conjur_v5_app_binding.rb
app/models/service_binding/conjur_v5_space_binding.rb
ci/integration/conjur/start

Pivotal Cloud Foundry recently became VMWare Tanzu Application Service (TAS),
and this commit updates our documentation to refer to TAS instead of PCF where
appropriate.
This commit also adds line breaks to reduce line length in the changed lines.
Connected to conjurinc/cloudfoundry-conjur-tile#43

Update READMEs to refer to TAS instead of PCF

---

CHANGELOG.md
app/controllers/application_controller.rb
app/models/org_space_policy.rb
ci/cf.yml
docker-compose.yml
features/bind.feature

Updates the service broker to return 404 on bind when the org/space policy branches are missing or on provision when the org/space creation fails.
Previously, (as described in #192) if the org / space branches were missing from policy, the bind request would return an unhelpful 500 response.
In this PR, we update the service broker to return 404 instead, with an error message that explains what is missing. We also update the Conjur CLI image from the docker-compose to use the updated `cyberark/conjur-cli:5` syntax.
Connected to #192

Return 404 when missing org / space policy branches rather than returning unhelpful 500

---

CHANGELOG.md
lib/conjur_client.rb
spec/lib/conjur_client_spec.rb

Previously, when `version` was called, we would parse the input into an integer. 
If no input was found, we would use `5`. 
However, this does not account for invalid input or empty strings.
This PR implements a simple ternary operator to validate input. 
If "4" is passed in, `4` will be used. Otherwise, we will use `5` as the default.
Spec tests were added to verify functionality 
Connected to #47

Default to 5 if CONJUR_VERSION is invalid

---

CHANGELOG.md
Gemfile
Gemfile.lock
NOTICES.txt
ci/integration/test-app/Gemfile.lock

Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
Bumps rack in both the main Gemfile/Gemfile.lock and the test-app Gemfile.lock to v2.2.3 to close CVE-2020-8184 and CVE-2020-8161 (neither of which directly impacted us).

Rack version bump to 2.2.3 in both main and test-app

---

Jenkinsfile

This uses new pipeline library functions to add the IP address of the Jenkins agent to the
AWS prefix list used to limit access to the PCF cluster and remove access once completed.

Update to add IP to list for security group access

---

CHANGELOG.md

In the next release, we'd like to announce deprecation for Conjur Enterprise v4.
Relates to #191

Add Conjur v4 deprecation to unreleased changelog

---

features/support/hooks.rb

Currently the Service Broker E2E tests do clean up of Tanzu orgs only
if tests are successful. This is causing 3 residual orgs on our Tanzu
platform each time E2E tests fail, and after a while, other builds start
failing because of resource limitations.
This change modifies the cleanup of orgs so that it is done
regardless of pass/fail result of test scenarios.
Resolves #219

Cleans up orgs in E2E tests unconditionally

---

Gemfile
Gemfile.lock
features/support/http_helper.rb

- Bumps Puma to 5.1.1
- An issue was found in our tests where we use `Content_Type`, and the
underscore was replaced by a `,`, due to a Puma patch (3.12.6).
Credit to @doodlesbykumbi for figuring out the issue!
Resolves #198

Bump Puma version

---

dev/dev_env_menu
spec/spec_helper.rb

When running the service broker UT, a deprecation warning is displayed about the use of
the :should contruct. This adds the explicit configuration so the warning is not displayed.
Below displays the error:
```=====================================================================
Running tests
=====================================================================
1) Run rspec unit tests				     4) Select from a list of Cucumber scenarios to test
2) Run integration (non-E2E) Cucumber tests	     5) Run a bash shell in test container
3) Select from a list of Cucumber features to test   6) Exit and clean up development environment
Please select tests to run: 1
Deprecation Warnings:
Using `stub_chain` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use …
```

Eliminate UT deprecation warning

---

Dockerfile.test

When we run the service broker bash shell, vi is not installed.
The user must run apt install vim.
This adds vim to the test container.
Resolves #230

Add vi to the service broker test bash shell.

---

CHANGELOG.md
Gemfile

The service broker displays a warning "**WARNING** You have not declared a Ruby version in your Gemfile."
This commit adds the Ruby version (same as Conjur) to the Gemfile so that it is explicit when the service broker
is installed in TAS.
When you install the service broker, you see a warning like:
```
Downloaded app package (14M)  
-----&gt; Ruby Buildpack version 1.8.27  
-----&gt; Supplying Ruby  
-----&gt; Installing bundler 1.17.3  
Copy [/tmp/buildpacks/85b47e8d42f9fa00e609eec0caebf608/dependencies/1b585b3a526373724c47492bbb271365/bundler-1.17.3-any-stack-b7502506.tgz]  
[31;1m**WARNING**[0m You have not declared a Ruby version in your Gemfile.  
Defaulting to 2.7.2  
See http://docs.cloudfoundry.org/buildpacks/ruby/index.html#runtime for more information.  
```
If the Ruby …

Specify Ruby version in Gemfile

---

CHANGELOG.md

Updates link in changelog to be absolute instead of relative, so that downstream release notes aggregation has valid links.
n/a

Update link in changelog

---

Dockerfile
Dockerfile.dev
Dockerfile.test

The Dockerfile must be pinned to the same version as the Gemfile, otherwise
the build fails in the pipeline.
n/a

Pin dev/test Dockerfiles to Ruby 2.5.8 to match Gemfile

---

.dockerignore
buildpack-health-check/go.mod
buildpack-health-check/go.sum

Bump golang.org/x/crypto to address CVE-2020-29652.
n/a

Bump golang.org/x/crypto to address CVE

---

CHANGELOG.md

Updates the changelog to be clear that in the new feature added to write org / space name in annotations, it will only work if you are using a version of Conjur that supports annotations on policy resources.
In trying to add an e2e test flow that validates annotations (see the [`integration-test-annotations` branch](https://github.com/cyberark/conjur-service-broker/compare/integration-test-annotations)), I discovered that our older Conjur instance running in AWS (v5.2.3) doesn't support annotations on policy resources.
This was added to `conjur-policy-parser` in [v3.0.3](https://github.com/cyberark/conjur-policy-parser/blob/conjur-oss/CHANGELOG.md#v303), which was included in Conjur Open Source [v1.3.7](https://github.com/cyberark/conjur/blob/master/CHANGELOG.md#137---2019-03-27) and …

Changelog notes Conjur version required for policy annotations

---

CHANGELOG.md

Adds a Changelog entry for Addressable version bump from 2.5.2 to 2.8.0.

Update Changelog for Addressable version bump

---

CHANGELOG.md
manifest.yml

The conjur-service-broker is failing to deploy on new releases of the ruby_buildpack (>= v1.8.38), which do not include the pinned Ruby version (2.5.8).
This PR explicitly sets the [ruby_buildpack](https://github.com/cloudfoundry/ruby-buildpack) buildpack to be used when deploying conjur-service-broker. This PR also pins the ruby_buildpack to [ruby-buildpack.git#v1.8.37](https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.8.37) which is the last version to include the pinned Ruby version (2.5.8) for conjur-service-broker.
Ruby 2.5.x versions were removed in [ruby-buildpack.git#v1.8.38](https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.8.38)
**NOTES:**
1. Prior to this change the service broker assumed that a buildpack would be autodetected to satisfy the needs of …

Explicitly specify ruby_buildpack for conjur-service-broker

---

Jenkinsfile

To avoid conflicts, such as`Service 'cyberark-conjur' is provided by multiple service brokers. Specify a broker by using the '-b' flag.`, it's best to lock the pipeline on "tas-infra" (the standard lock name for our Tanzu infrastructure). This will avoid failure when .e.g. a pipeline for https://github.com/conjurinc/cloudfoundry-conjur-tile is running at the same time.
Resolves -

Lock pipeline on tas-infra to avoid contention

---

buildpack-health-check/Dockerfile

When we upgraded cyberark/conjur-service-broker's buildpack-health-check to Go 1.17, we didn't update the Dockerfile to use a new base image. Update it to a newer one, both for consistency and Snyk indicates it will reduce the number of known issues in the base.
- Updated golang base image in buildpack-health-check/Dockerfile
CyberArk internal issue link: [ONYX-16436](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-16436)
CHANGELOG update
changes, or

Update Golang version in health-check Dockerfile

---

CHANGELOG.md
Gemfile.lock
NOTICES.txt
buildpack-health-check/go.mod
buildpack-health-check/go.sum
tests/integration/test-app/Gemfile.lock

Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
Remove dependency on gopkg.in/yaml.v3 prior to v3.0.1
Upgrades conjur-api-go to v0.10.1
CyberArk internal issue: CONJSE-1374
*At least 1 todo must be completed in the sections below for the PR to be
merged.*
CHANGELOG update
changes, or

Upgrade conjur-api-go to v0.10.1

---

dev/test_e2e

This hides any errors that occur on this step.
The redirect is removed so that errors will be shown in future builds.

Remove Stderr redirect from Cert Fetch

---

Jenkinsfile

TAS V3 is causing problems, this commit is to pin back to latest 2.x so work can continue. V3 compatibility will be a separate effort.
Related: ONYX-26801

Pin TAS to 2.13

---

CHANGELOG.md
buildpack-health-check/go.mod
buildpack-health-check/go.sum

Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
Remove indirect dependency gopkg.in/yaml.v2 versions less than / equal to 2.2.4
Updated conjur-api-go version to 0.10.2

Update conjur-api-go to v0.10.2

---

.github/CODEOWNERS
.trivyignore

Now that this project has been upgraded to Ruby 3.1, we don't need the bits we put in place to make sure we didn't fall victim to some bundler CVEs. Clean them up.
- Removed the CODEOWNERS entry for Gemfile and Gemfile.lock that required security architects review on changes
- Removed the .trivyignore for the CVEs

Remove no longer needed CVE protections

---

CHANGELOG.md
Gemfile.lock
NOTICES.txt
tests/integration/test-app/Gemfile.lock

This pull request upgrades 'rack' from 2.2.6.2 to 3.0.4.2 to resolve security issue CVE-2023-27630.
- Upgraded rack in Gemfile.lock
- Upgraded rack in tests/integration/test-app/Gemfile.lock
- Updated NOTICES.txt
- Updated CHANGELOG.md
CHANGELOG update
changes, or

Upgrade rack from 2.2.6.2 to 2.2.6.3 to resolve CVE-2023-27530
